Makes Lua's `print()` write to Blightmud's screen.
LiquidityC/Blightmud pull request #165
Opened 2020-10-30 23:15 UTC by xvxx

Just a tiny little thing. This makes Lua's `print()` write to Blightmud's screen.

Before:

```
> /lua print 'oh no'
(no output)
```

After:

```
> /lua print 'heyoo'
heyoo
```

2020-10-30 23:17 UTC, LiquidityC commented
Awesome sauce! Just one note. Dropping a review comment.

2020-10-30 23:18 UTC, LiquidityC requested changes
This is great. I've been thinking about fixing this. One note. Can you extend the documentation in `lua_blight.md`. Next to the `blight:output` documentation that this also works now?

2020-10-30 23:20 UTC, Xandaros commented
Hmm, do we really want to document `print`, though?
I feel like that's not on us, since it's a standard Lua function and the new behaviour is exactly what you would expect it to do

2020-10-30 23:22 UTC, LiquidityC commented
I was thinking in the lines of "Luas standard `print` function utilizes blight:output". Just as a short note. Otherwise people won't have the information available to them no big section on it.

2020-10-31 00:17 UTC, xvxx commented
@Xandaros I think it's worth mentioning because there are other Lua functions which don't yet work as you'd expect, like `io.write()` usually prints sans newline. Not sure if it's worth converting all of them or not. Maybe?

2020-10-31 00:26 UTC, LiquidityC approved these changes

2020-10-31 00:27 UTC, LiquidityC commented
We won't mess with `io.write` that might mess up file writing and we don't want that.

2020-10-31 00:27 UTC, merged